### ISSUE TITLE
-webkit and -moz prefixes missing in output

### ISSUE THREAD

**Issue by PandaWhisperer** [Igosuki/compass-mixins#22]
I have noticed one issue with the latest version. The stylesheet I'm using has the following mixin:

``` css
@mixin flexbox {
  display: -webkit-box !important;
  display: -moz-box !important;
  display: -ms-box !important;
  display: -o-box !important;
  display: box !important;
}

// the mixin is used in other places, but also this:
.flexbox {
  @include flexbox;
}
```

For some reason, after compilation, this comes out to 

``` css
.flexbox {
  display:-ms-box !important;
  display:-o-box !important;
  display:box !important;
}
```

In other words, the `-webkit-` and `-moz-` versions are missing. The same appears to be true for the other classes that use the mixin. Other mixins related to flexbox, for instance `box-orient`, work fine with these prefixes. 

Not sure what's going on here and whose fault it is (I'm using `harp`, which uses `node-sass` to compile SCSS). May or may not relate to #15.

Any thoughts on this?
