### ISSUE TITLE
Helper functions font-files and font-url are missing, resulting in broken font-face mixins

### ISSUE THREAD

**Issue by hashworks** [Igosuki/compass-mixins#36]
The regarded ruby sources are [font_files.rb](https://github.com/Compass/compass/blob/master/core/lib/compass/core/sass_extensions/functions/font_files.rb) and [urls.rb](https://github.com/Compass/compass/blob/master/core/lib/compass/core/sass_extensions/functions/urls.rb).

**Comment by hashworks** [comment]
The url-functions issue already exists, see #20.

**Comment by kidd001** [comment]
Does it explain why my font-face mixin didn't get compiled at all?

**Comment by hashworks** [comment]
Propably not. In my case they came out fine, but with font-url and font-files in them.

**Comment by Igosuki** [comment]
These haven't been implemented yet, I've added them to the migration issue

**Comment by vredeling** [comment]
Is this project abandoned? Seems weird to implement the font-face mixin and not implement the font-files mixin.

**Comment by SergiArias** [comment]
My workaround (by using compass with yeoman webapp) was to create this function:
`@function font-url($path) { @return url('#{$path}'); }`

And this one:

```
@function font-files($font-name, $path, $formats...) {
  $full: ''; 
  @for $i from 1 through length($formats) {
    $full: $full + 'url("#{$path}.' + nth($formats,$i);
    @if nth($formats,$i) == 'ttf' {
      $full: $full + '") format("' + 'truetype")'
    }@else if nth($formats,$i) == 'svg' {
      $full: $full + '#' + $font-name + '") format("' + nth($formats,$i) + '")';
    }@else {
      $full: $full + '") format("' + nth($formats,$i) + '")';
    }
    @if $i!=length($formats) { $full: $full + ', ';}
  }
  @return unquote($full);
}
```

**Comment by alphaelf** [comment]
@SergiArias  thanks for add helper funtions.

however `font-files` function must fix `$font-name` on: 
`$full: $full + 'url("#{$path}.' + nth($formats,$i);`

so for use compass `font-face` mixin:
- 1 copy this function to top of your e.g. `fonts.scss` file:
```scss
@function font-url($path) {
	@return url('#{$path}');
}
@function font-files($font-name, $path, $formats...) {
  $full: '';
  @for $i from 1 through length($formats) {
    $full: $full + 'url("#{$path}/#{$font-name}.' + nth($formats,$i);
    @if nth($formats,$i) == 'ttf' {
      $full: $full + '") format("truetype")';
    }@else if nth($formats,$i) == 'svg' {
      $full: $full + '#' + $font-name + '") format("svg")';
    }@else {
      $full: $full + '") format("' + nth($formats,$i) + '")';
    }
    @if $i!=length($formats) { $full: $full + ', ';}
  }
  @return unquote($full);
}
```
- 2 use mixin this way:
```scss
$font-path: "/public/fonts/roboto";
@include font-face('Roboto',
	font_files(roboto,$font-path,ttf,woff,woff2,svg), '#{$font-path}/roboto.eot',
	normal,
  normal
);
```
