### ISSUE TITLE
Major prefixing problems

### ISSUE THREAD

**Issue by OnkelTem** [Igosuki/compass-mixins#58]
Original issue:
> Basically this doesn't work:
> ```scss
>  @include background(url('image.png'), linear-gradient(left, red, white));
> ```
> as it doesn't prefix linear-gradients.

**UPDATE**

Actually even this simple code works incorrectly:
```scss
@include background(url('image.png') no-repeat center center, red);
```
as it results to CSS code:
```css
background: -webkit-url("/build/images/i-plus.png") no-repeat center center, red
```
where ```url``` is prefixed. This happens becuase of the ```prefixed()``` function:

```scss
@function prefixed($prefix, $property1, $property2:null, $property3:null, $property4:null, $property5:null, $property6:null, $property7:null, $property8:null, $property9:null) {
  $properties: $property1, $property2, $property3, $property4, $property5, $property6, $property7, $property8, $property9;
  $prefixed: false;
  @each $item in $properties {
    @if type-of($item) == 'string' {
      $prefixed: $prefixed or str-index($item, 'url') != 1 and str-index($item, 'rgb') != 1 and str-index($item, '#') != 1;
    } @elseif type-of($item) == 'color' {
    } @elseif $item != null {
      $prefixed: true;
    }
  }
  @return $prefixed;
}
```
Which erroneously supposes that **any list should be prefixed**:
```scss
    } @elseif $item != null {
      $prefixed: true;
    }
```
