### ISSUE TITLE
animation mixin only adds the animation-name property

### ISSUE THREAD

**Issue by yoavniran** [Igosuki/compass-mixins#75]
Hi,
Im using this include in a class style in my scss:  
```scss
.my-arrow{
    @include animation(arrow-bounce 0.5s linear 0s infinite normal forwards initial);
}
```
the result in my css is:

```css
.my-arrow{
   -webkit-animation: arrow-bounce;
      -moz-animation: arrow-bounce;
      -ms-animation: arrow-bounce;
      -o-animation: arrow-bounce;
      animation: arrow-bounce;
}
```

None of the other properties is used... am I doing something wrong?

thanks
